server:
  port: 7001

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/TimoLX/risk-config
          search-paths: default
          username: 694137581@qq.com
          password: zlx6621980
